backend:
  name: git-gateway
  branch: next # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  repo: brandnewguys/companysite # Path to your GitHub repository
# This line should *not* be indented
publish_mode: editorial_workflow
logo_url: https://brandnewguys.co/img/bng-black.svg
local_backend: true

# This line should *not* be indented
media_folder: "/src/static/img/uploads/" # Media files will be stored in the repo under img/portfolio-content/Netlify-cms
public_folder: "/"

collections:
  - name: deepcuts
    label: Podcasts
    label_singular: Podcasts
    create: true
    folder: "/src/deepcuts"
    fields:
      - {label: "Title", name: title, widget: "string"}
      - {label: "Recording date", name: "recording_date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Spotify", name: "spotify_url", widget: "string", required: false}
      - {label: "Apple", name: "apple_url", widget: "string", required: false}
      - {label: "Google", name: "google_url", widget: "string", required: false}
      - {label: "Stitcher", name: "stitcher_url", widget: "string", required: false}
      - {label: "Radiopublic", name: "radiopublic_url", widget: "string", required: false}
      - {label: "Embedded player url", name: "embedded_player", widget: "string", required: false}
      - label: "Guests"
        name: "guests"
        label_singular: "guest"
        widget: "list"
        allow_add: true
        fields:
              - { label: Guestname, name: guest_name, widget: string }
              - { label: Guest url, name: guest_url, widget: string }
      - label: Body
        name: body
        widget: markdown

  - label: "Cases"
    name: "cases"
    folder: "/src/cases"
    create: true
    slug: "{{ priority }}-{{ title }}"
    fields: 
      - {label: "Priority", name: "priority", widget: "string"}
      - {label: "Title", name: title, widget: "string"}
      - {label: "Image", name: "img", widget: "image", allow_multiple: false}
      - {label: "Url", name: "url", widget: "string"}

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "/src/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Background", name: "background", widget: "image", allow_multiple: false}
          - {label: "Logo", name: "logo", widget: "image", allow_multiple: false}
          - {label: "Version", name: "version", widget: "string"}
          - label: "Location"
            name: "location"
            widget: "object"
            summary: "{{fields.label}}"
            fields: 
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
          - {label: "Instagram url", name: "instagram", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Introduction", name: "intro", widget: "string"}

      - label: "Now Playing Page"
        name: "nowplaying"
        file: "/src/static/nowplaying.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "nowplaying"}
          - {label: "Client", name: "client", widget: "string"}
          - {label: "Wifinetwork", name: "wifi_network", widget: "hidden", default: "wecaneat"}
          - {label: "Wifi", name: "wifi_code", widget: "hidden", default: "BNG"}
          - {label: "Agenda 1", name: "agenda1", widget: "string"}
          - {label: "Agenda 2", name: "agenda2", widget: "string"}
          - {label: "Agenda 3", name: "agenda3", widget: "string"}
          - {label: "Agenda 4", name: "agenda4", widget: "string"}
          - {label: "Balie animatie", name: "balie_movie", widget: "file"}
      